// All player-facing text. Keep UI strings here so the game can be translated later.

import type { NodeKind } from '../systems/map';

export const STRINGS = {
  title: 'LeagueRogue',
  tagline: 'A League of Legends roguelike',
  howToPlay: [
    'Pick a starter, then choose your path through each map. Every node is a fight, a recruit, an item, or a rest.',
    'Battles play out automatically: your front champion fights theirs until one falls, then the next steps in.',
    'Win to earn XP for the whole team. Knocked-out champions sit out until a Fountain or a boss win.',
    'Beat the region boss at the end of each map. Lose a battle and the run is over.',
  ],
  shortRun: 'Short run',
  shortRunDesc: '3 region bosses, faster leveling. About 15 minutes.',
  fullRun: 'Full run',
  fullRunDesc: '8 region bosses, the full climb to level 18.',
  armoryRun: 'Armory run',
  armoryRunDesc: '8 bosses. No item nodes: earn gold and shop after every region. 3 item slots, slower leveling at high levels.',
  conquestRun: 'Conquest',
  conquestRunDesc: 'Conquer the regions of Runeterra one by one. Earn Blue Essence, unlock champions and buy runes between runs.',
  essence: 'Blue Essence',
  essenceHint: 'Blue Essence: earned from fights in Conquest runs (kept even if you lose), spent in the rune shop.',
  essenceGained: (n: number) => `+${n} essence`,
  worldMapTitle: 'Conquest of Runeterra',
  worldMapIntro: 'Start in Demacia. Each region you conquer opens harder ones. Enemies there are stronger, so give your champions runes.',
  runeShop: 'Rune shop',
  tier: (n: number) => `Tier ${n}`,
  regionLocked: 'Locked',
  regionOpen: 'Not conquered yet',
  regionConquered: 'Conquered',
  lockedHint: 'Conquer a neighboring region first.',
  enemyStrength: (pct: number) => (pct > 0 ? `Enemies +${pct}% HP, damage and resists` : 'Normal enemies'),
  recommendedPower: (n: number) => `Recommended rune power: ${n}`,
  yourPower: (n: number) => `Your best six: ${n}`,
  powerHint: 'Rune power = total rune ranks on a champion. "Your best six" averages your six highest.',
  conquer: 'Conquer',
  reconquer: 'Play again',
  collection: (n: number, total: number) => `Collection: ${n} / ${total} champions`,
  runesTab: 'Runes',
  championsTab: 'Champions',
  runeShopIntro: 'Runes give a champion bonus stats from the start of every Conquest run. Ranks stack.',
  unlockIntro: 'Unlocked champions can be your starter and show up as recruits in Conquest runs.',
  runePowerLabel: (n: number, max: number) => `Rune power ${n} / ${max}`,
  runeRankLabel: (rank: number, max: number) => `Rank ${rank} / ${max}`,
  runeEffect: (stats: string, pct: number) => `+${pct}% ${stats} per rank`,
  upgrade: (cost: number) => `Upgrade · ${cost}`,
  maxRank: 'Max rank',
  unlock: (cost: number) => `Unlock · ${cost}`,
  owned: 'Owned',
  bonusStats: 'Bonus stats',
  worldMap: 'World map',
  conquestHeader: (region: string) => `${region} conquest`,
  rewardTitle: 'Essence earned',
  rewardBattles: (n: number) => `Fights: +${n}`,
  rewardClear: (n: number) => `Conquest bonus: +${n}`,
  rewardFirstClear: (n: number) => `First conquest: +${n}`,
  rewardTotal: (n: number) => `Total: +${n} essence`,
  newRegionsOpen: (names: string) => `New regions open: ${names}`,
  conquestVictoryText: (region: string) => `${region} is yours.`,
  abandonConfirm: 'Abandon this run? In Conquest you keep the essence earned so far.',
  goldHint: 'Gold: earned from fights, spent in the shop after each region.',
  goldGained: (gold: number) => `+${gold} gold`,
  shopTitle: 'Shop',
  shopIntro: 'Buy as many items as you can afford. Equip them from your team panel; spares stay in the bag.',
  buy: (cost: number) => `Buy · ${cost} gold`,
  sold: 'Bought',
  reroll: (cost: number) => `Reroll · ${cost} gold`,
  sell: (price: number) => `Sell · ${price}`,
  sellHint: 'Sell spare items from your bag for half price.',
  leaveShop: 'Leave shop',
  chooseStarter: 'Choose your starter',
  recruitTitle: 'Recruit a champion',
  recruitFull: 'Your team is full. Choose who leaves to make room.',
  itemTitle: 'Choose an item',
  itemGiveTo: 'Give it to…',
  keepInBag: 'Keep in bag',
  levelUpTitle: (levels: number) => `Choose a champion to gain ${levels} level${levels === 1 ? '' : 's'}`,
  skip: 'Skip',
  back: 'Back',
  continue: 'Continue',
  newRun: 'New run',
  mainMenu: 'Main menu',
  guide: 'Guide',
  details: 'Details',
  regionBonuses: 'Region bonuses',
  regionHint: 'Counts champions who can still fight.',
  team: 'Team',
  bag: 'Bag',
  bagEmpty: 'No spare items.',
  unequip: 'Unequip',
  noItem: 'No item',
  orderHint: 'Front of the list fights first.',
  mapHeader: (n: number, total: number) => `Map ${n} / ${total}`,
  bossAhead: 'Boss',
  fountainTitle: 'Fountain',
  fountainText: 'Your champions are fully healed and back on their feet.',
  battleWonTitle: 'Victory!',
  xpGained: (xp: number) => `+${xp} XP for the whole team`,
  levelGain: (name: string, from: number, to: number) => `${name}: level ${from} → ${to}`,
  ultUnlocked: 'Ultimate unlocked!',
  ultRankUp: 'Ultimate rank up!',
  mapCompleteTitle: (boss: string) => `${boss} defeated!`,
  mapCompleteText: 'Your whole team is healed and revived. The next region awaits.',
  gameOverTitle: 'Defeat',
  gameOverText: (maps: number, battles: number) => `You cleared ${maps} ${maps === 1 ? 'map' : 'maps'} and won ${battles} battles.`,
  victoryTitle: 'Victory!',
  victoryText: 'Every region boss has fallen. The Rift Gauntlet arrives in a later version.',
  battleSpeed: 'Speed',
  skipBattle: 'Skip',
  fight: { camp: 'Jungle camp', rival: 'Rival summoner', boss: 'Boss battle' } as const,
  vs: 'vs',
  ultimate: 'Ultimate',
  unlocksAt: (level: number) => `unlocks at level ${level}`,
  cooldown: (turns: number) => (turns === 0 ? 'every turn' : `waits ${turns} turn${turns === 1 ? '' : 's'}`),
  legalDisclaimer:
    "LeagueRogue isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone " +
    'officially involved in producing or managing Riot Games properties. Riot Games, and all associated properties ' +
    'are trademarks or registered trademarks of Riot Games, Inc.',
} as const;

export const NODE_INFO: Record<NodeKind, { icon: string; label: string; hint: string }> = {
  camp: { icon: '🐺', label: 'Jungle camp', hint: 'An easy fight. +XP.' },
  rival: { icon: '⚔️', label: 'Rival summoner', hint: 'A tougher team fight. More XP.' },
  recruit: { icon: '🤝', label: 'Recruit', hint: 'Choose 1 of 3 champions to join your team.' },
  item: { icon: '🗡️', label: 'Item', hint: 'Choose 1 of 3 items.' },
  fountain: { icon: '⛲', label: 'Fountain', hint: 'Fully heal and revive your team.' },
  levelup: { icon: '⭐', label: 'Level up', hint: 'One champion gains levels.' },
  boss: { icon: '👑', label: 'Region boss', hint: 'Defeat the boss to clear the map.' },
};
