// All player-facing text. Keep UI strings here so the game can be translated later.

import type { NodeKind } from '../systems/map';

export const STRINGS = {
  title: 'LeagueRogue',
  tagline: 'A League of Legends roguelike',
  howToPlay: [
    'Pick a starter, then choose your path through each map. Every node is a fight, a recruit, an item, or a rest.',
    'Battles play out automatically: your front champion fights theirs until one falls, then the next steps in.',
    'Win to earn XP for the whole team. Knocked-out champions sit out until a Fountain or a boss win.',
    'Beat the region boss at the end of each map. Lose a battle and the run is over.',
  ],
  shortRun: 'Short run',
  shortRunDesc: '3 region bosses, faster leveling. About 15 minutes.',
  fullRun: 'Full run',
  fullRunDesc: '8 region bosses, the full climb to level 18.',
  armoryRun: 'Armory run',
  armoryRunDesc: '8 bosses. No item nodes: earn gold and shop after every region. 3 item slots, slower leveling at high levels.',
  goldHint: 'Gold: earned from fights, spent in the shop after each region.',
  goldGained: (gold: number) => `+${gold} gold`,
  shopTitle: 'Shop',
  shopIntro: 'Buy as many items as you can afford. Equip them from your team panel; spares stay in the bag.',
  buy: (cost: number) => `Buy · ${cost} gold`,
  sold: 'Bought',
  reroll: (cost: number) => `Reroll · ${cost} gold`,
  sell: (price: number) => `Sell · ${price}`,
  sellHint: 'Sell spare items from your bag for half price.',
  leaveShop: 'Leave shop',
  chooseStarter: 'Choose your starter',
  recruitTitle: 'Recruit a champion',
  recruitFull: 'Your team is full. Choose who leaves to make room.',
  itemTitle: 'Choose an item',
  itemGiveTo: 'Give it to…',
  keepInBag: 'Keep in bag',
  levelUpTitle: (levels: number) => `Choose a champion to gain ${levels} level${levels === 1 ? '' : 's'}`,
  skip: 'Skip',
  back: 'Back',
  continue: 'Continue',
  newRun: 'New run',
  mainMenu: 'Main menu',
  guide: 'Guide',
  details: 'Details',
  regionBonuses: 'Region bonuses',
  regionHint: 'Counts champions who can still fight.',
  team: 'Team',
  bag: 'Bag',
  bagEmpty: 'No spare items.',
  unequip: 'Unequip',
  noItem: 'No item',
  orderHint: 'Front of the list fights first.',
  mapHeader: (n: number, total: number) => `Map ${n} / ${total}`,
  bossAhead: 'Boss',
  fountainTitle: 'Fountain',
  fountainText: 'Your champions are fully healed and back on their feet.',
  battleWonTitle: 'Victory!',
  xpGained: (xp: number) => `+${xp} XP for the whole team`,
  levelGain: (name: string, from: number, to: number) => `${name}: level ${from} → ${to}`,
  ultUnlocked: 'Ultimate unlocked!',
  ultRankUp: 'Ultimate rank up!',
  mapCompleteTitle: (boss: string) => `${boss} defeated!`,
  mapCompleteText: 'Your whole team is healed and revived. The next region awaits.',
  gameOverTitle: 'Defeat',
  gameOverText: (maps: number, battles: number) => `You cleared ${maps} ${maps === 1 ? 'map' : 'maps'} and won ${battles} battles.`,
  victoryTitle: 'Victory!',
  victoryText: 'Every region boss has fallen. The Rift Gauntlet arrives in a later version.',
  battleSpeed: 'Speed',
  skipBattle: 'Skip',
  fight: { camp: 'Jungle camp', rival: 'Rival summoner', boss: 'Boss battle' } as const,
  vs: 'vs',
  ultimate: 'Ultimate',
  unlocksAt: (level: number) => `unlocks at level ${level}`,
  cooldown: (turns: number) => (turns === 0 ? 'every turn' : `waits ${turns} turn${turns === 1 ? '' : 's'}`),
  legalDisclaimer:
    "LeagueRogue isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone " +
    'officially involved in producing or managing Riot Games properties. Riot Games, and all associated properties ' +
    'are trademarks or registered trademarks of Riot Games, Inc.',
} as const;

export const NODE_INFO: Record<NodeKind, { icon: string; label: string; hint: string }> = {
  camp: { icon: '🐺', label: 'Jungle camp', hint: 'An easy fight. +XP.' },
  rival: { icon: '⚔️', label: 'Rival summoner', hint: 'A tougher team fight. More XP.' },
  recruit: { icon: '🤝', label: 'Recruit', hint: 'Choose 1 of 3 champions to join your team.' },
  item: { icon: '🗡️', label: 'Item', hint: 'Choose 1 of 3 items.' },
  fountain: { icon: '⛲', label: 'Fountain', hint: 'Fully heal and revive your team.' },
  levelup: { icon: '⭐', label: 'Level up', hint: 'One champion gains levels.' },
  boss: { icon: '👑', label: 'Region boss', hint: 'Defeat the boss to clear the map.' },
};
